### ISSUE TITLE
[STAC] stac-prepare-nodes failed.

### ISSUE THREAD

**Issue by mrsiano** [openshift/svt#267]
stac-prepare-node.py execute ansible playbook which include sort of tasks.
the last task (tuned-adm verify) https://github.com/openshift/svt/blob/master/networking/synthetic/stac-prepare-nodes.yaml#L30 always fails due to real tuned problem.

as I spoke with jeremy, verify wont pass until /proc/cmdline includes the flags.
since we deal with tuned bootloader for cmd, we have to reboot the machine.

so it looks like we need to skip that verification step (as fast and easy solution)
or use one of the following methods:
1. when running svt from the master node machine (just as I did):
- let ansible to reboot the machine.
- run another script which includes some verification steps without tuned-adm verify command.
2. when running it from a remote machine:
- let ansible reboot the machine 
- wait for power up
- run the tuned-adm verification. 
note: we could have some slow ansible execution time, due WAN latency.

workaround:
reboot manually.

@vikaschoudhary16 
@jeremyeder

**Comment by jeremyeder** [comment]
I think it's OK to have ansible reboot the machines.

Just need to coordinate where you are running ansible from.

* Jenkins:  ansible-based reboots will be OK if we create a Jenkins job, ansible will be running on a slave.
* Use one of the test machines for running ansible, it would be a problem, no?
* Somehow introducing a 3rd machine into the mix?  (is it your workstation, which is why you mentioned WAN latency?

**Comment by mrsiano** [comment]
@jeremyeder 
ok, so I'll create a PR to have ansible reboot, for both case if it's an jenkis job or a 3rd machine (workstation)

and sure, this stage was part of node preparation so it should be just once.
related to the stac-prepare-script.
