### ISSUE TITLE
Restructure cluster-loader code for better readability

### ISSUE THREAD

**Issue by hroyrh** [openshift/svt#60]
I would like everyone's suggestions on this. @timothysc @jeremyeder @sjug @mffiedler

**Comment by sjug** [comment]
Once you take a good look at it, it's not *that* bad. What did you have in mind specifically?
Re-ordering the functions or changing some of the logic?

**Comment by mffiedler** [comment]
Things I would like to see (and contribute to)

- break out OC/kubectl command processing to a separate lib - see #5 
- remove duplicate logic for oc vs kubectl where ever possible
- don't pass "globalvars" around everywhere.  Just make it a real global.
- remove the cleaning functionality 
- add some tests (or at least additional regression config files).
- add option (or part of debug option) to keep temporary json template files around for inspection

**Comment by jeremyeder** [comment]
Trello card(s) please.

**Comment by mffiedler** [comment]
See also: https://trello.com/b/M1bpo55E/scalability

**Comment by rflorenc** [comment]
+1 @mffiedler bullet point on adding testing. If we're re-factoring we might start adding unit tests as well.
TDD would be even better.

**Comment by timothysc** [comment]
Do folks want to use re-structuring as a means to learn go?  

It may be a bit conflating, but it then acts as a forcing function.

**Comment by sjug** [comment]
@timothysc: I would like to be part of that if we are going that route.

**Comment by rflorenc** [comment]
@timothysc @jeremyeder @sjug @mffiedler
Re-writting in go sounds like a good idea, especially if we think in advance about how to re-structure the code in order to make it easier to integrate or 'pluggable' with Openshift or it's tests.
But even before all that, just having  `encoding/json` available would already be a huge plus.

Having things like viper ( @jayunit100 ) or ginkgo would probably make sense too.
Just my opinion, as I was barely involved with cluster-loader development.

**Comment by ravisantoshgudimetla** [comment]
I have been going through code to get some familiarity. If I may, I wish to suggest few things. Please feel to correct me, in case you guys think I am making some wrong assumptions:

- How about defining a class for functions in utils.py. The flow will be something like current cluster-loader.py becomes parser.py in "utils/" as it is technically doing only parsing of file and utils.py becomes a class called OC-Operations and this become new cluster-loader.py with instance variable called global-variables and all the methods in class can access that variable(with this we don't have to pass variables around) and writing test-cases becomes easier.

- Even if we want to use golang, we can follow the same approach with class replaced with struct. We can use something like cobra, for getting all the command line options just like how kubernetes or openshift works.

I could have made some obvious mistake, as I am new to code, so please go ahead and tear apart any of suggestions, if you guys think, I am talking non-sense.

**Comment by rflorenc** [comment]
I took a first stab at this since I was doing load testing at a client recently.

https://github.com/rflorenc/openshift-cluster-loader

It's just a base idea that doesn't break much functionality.

For now:
- adds some sanity checks and exits early if user not logged in.
- separates argparse cmdline arguments and adds a base config file (.config.cfg).
- Refactored utils.py to oc.py base class. See `cmd/oc.py`
- removed kubectl support.
- left variable names the same as before.

An idea would be to add plugin functionality in the style of what Tuned does, instead of adding new code between functions in `utils.py`:
e.g.: EBS plugin, Ceph plugin, Gluster plugin, jmeter plugin, prometheus plugin...

**Comment by mffiedler** [comment]
Hi @rflorenc  - the golang version of cluster-loader is what is actively maintained.   See:  https://github.com/openshift/origin/tree/master/test/extended/cluster

/cc: @sjug

**Comment by rflorenc** [comment]
Thank you. Will definitely try it out.
