### ISSUE TITLE
aws-cli wrapper

### ISSUE THREAD

**Issue by jeremyeder** [openshift/svt#70]
For billing purposes, we need to enforce some uniformity around creating AWS instances.  To do this, I  propose wrapping the AWS CLI utility with our own script that we'll carry in svt.

A typical invocation is:

$ aws ec2 run-instances --image-id $IMAGE_ID --count $COUNT --instance-type $INSTANCE_TYPE --key-name $SSH_KEY_NAME --subnet $SUBNET --security-group-ids $SGID

The script capabilities should allow for customization of:
- Image ID, but it should default to our latest.  Default is latest AMI, and we will update the script in svt whenever the AMI is updated.  This way everyone always uses the latest unless the choose otherwise.
- Count, instance count is variable of course.  No default, fail if not specified.
- Instance Type, no default, fail if not specified.
- key-name should be hard-coded
- subnet should be hard-coded
- security group should be hard-coded
- disk image size, I think we want to offer this
- storage type, gp2/io1

Instance tags:
- group, for billing purposes we'd like to track which group created the instance (right now this would be qe or perf).  No default, fail if not specified
- username, the aws account username who created the instance

Few other thoughts:
- "hard-coded" could mean it comes from a config file, too I guess...up to you.
- If anyone ever needs to customize things the script doesn't provide, they can always use the CLI tool manually.

Anything I missed?

/cc @sjug

**Comment by mffiedler** [comment]
We'd have to get this integrated with Flexy,  cc:  @akostadinov

**Comment by jeremyeder** [comment]
Agreed...since flexy is not always used for setting up AWS instances -- although I'd argue it probably should be.  Maybe the fix here then is more about adding this feature to flexy?

**Comment by akostadinov** [comment]
What kind of integration with flexy job are you guys suggesting.

I would not right away reject the idea without listening to you but I'm somehow skeptical about it. In flexy you can already launch instances as flexibly as the AWS API allows. Although I understand if teams want to use more standard tools. Ideally the upcoming official installers should suffice.
If you want to run instances with command line, that might be possible if you wrap cli calls into an ansible playbook and generate necessary hosts data structure (probably reading JSON with ruby and initialize some objects).

I'm open to help with implementation of the bridge between a launcher playbook and generating the necessary hosts structure because at some point that might be needed anyway, when we want to integrate with upcoming installers which will also launch VMs from ansible.

**Comment by mffiedler** [comment]
cluster-loader enhancements should be requested for the golang version in the openshift-tests binary: https://github.com/openshift/origin/tree/master/test/extended/cluster
